#ifndef ERRORS_H
#define ERRORS_H

#include "global.h"

extern int fatalError;

typedef enum {
    ERR_MEM_ALLOC = 1,
    ERR_FILE_OPEN,
    ERR_IO,

    ERR_LINE_TOO_LONG,
    ERR_UNKNOWN_LINE_TYPE,
    ERR_INSERT_EMPTY_LINE_FAIL,

    ERR_MACRO_EXPANSION_FAIL,
    ERR_ILLEGAL_MACRO_NAME,

    ERR_SYMBOL_NOT_FOLLOWED,
    ERR_DUPLICATE_SYMBOL,
    ERR_UNDEFINED_SYMBOL,
    ERR_SYMBOL_INVALID_LEN,
    ERR_RESERVED_NAME,

    ERR_INVALID_COMMAND,

    ERR_TOO_MANY_OPERANDS,
    ERR_MISSING_OPERANDS,
    ERR_INVALID_OPERAND,

    ERR_INVALID_ADDRESSING_METHOD,

    ERR_INVALID_INTEGER,
    ERR_NUMBER_OUT_OF_RANGE,
    ERR_INVALID_NUMBER_FORMAT,

    ERR_DIR_NO_PARAM,

    ERR_STR_TOO_MANY_PARAMS,
    ERR_STRING_TOO_SHORT,
    ERR_STRING_MISSING_QUOTES,

    ERR_MAT_INVALID_DIM,
    ERR_MAT_TOO_MANY_VALUES,
    ERR_MAT_INVALID_VALUE,
    ERR_MAT_INVALID_REGISTERS,
    ERR_MAT_ADDRESS_ILLEGAL_LEN,

    ERR_INVALID_REGISTER,

    ERR_ENTRY_SYMBOL_NOT_FOUND,
    ERR_ENTRY_SYMBOL_DEFINED_EXTERN,

    ERR_CODE_IMAGE_OVERFLOW,
    ERR_ALIGNMENT,
    ERR_INTERNAL,
    ERR_SYNTAX
} errorType;

void setFatalError(int lineNum, errorType type);
const char *getErrMessage(errorType type);

#endif